services:
  dev:
    build: .
    volumes:
      - .:/app
      - dev-home:/home/dev/
      - dev-bundle-cache:/usr/local/bundle
    working_dir: /app
    env_file: .env
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - MISE_TRUSTED_CONFIG_PATHS=/app

volumes:
  dev-home:
  dev-bundle-cache:
